---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    #driver_config:
      #provision_command:
      #- curl -L https://www.chef.io/chef/install.sh | bash
      #require_chef_omnibus: false

suites:
  - name: default
    run_list:
      - recipe[hello]
    attributes:
